### PR TITLE
Create Word List extension

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/1)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
Right now the word list extension will appear in a docked tab. In PT9 it's a floating window. Do we want it to appear as a floating window in P.B too?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/1#-:-NhhXr7Q1VJa5oCTpEjp:b-oh02zq)* status: 0 of 12 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/1#-:-NhhYSQ9BbOeoNIUprey:b-n4rtmo)* status: 0 of 12 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
If there's multiple occurences of the same word in the same verse, it will add multiple entries for them and highlight the proper one


> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/1#-:-NhhYhhbBO9sHDIbXg-D:b-obk42j)* status: 0 of 12 files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: :tada: Thanks for all the hard work! So exciting!

> Reviewed 12 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/1#-:-NhlOFQW1NVGqOOovsyr:bph8owq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
