### PR TITLE
Add open word list command

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3)

### CODE REVIEW

**Review by katherinejensen00 — CHANGES_REQUESTED** [review]
Looks pretty good. I just had one question.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3#-:-Ni071mZ25mfgPKGYM57:bqn9a04)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/main.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3#-Ni06cmGB_WEprp3KbVL:-Ni06cmGB_WEprp3KbVM:bqd63ap) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/9e4114ff7b18c440c6a39c5dfddd76b450e68616/src/main.ts#L39)):*
> ```XML
>       }
>     } catch (e) {
>       logger.error(`Text collection web view provider error: Could not get project metadata: ${e}`);
> ```

Is this supposed to say Wordlist instead of text collection?

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/main.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3#-Ni06cmGB_WEprp3KbVL:-Ni0IJgD2QybDOQxHDJR:b-gks9e0) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/9e4114ff7b18c440c6a39c5dfddd76b450e68616/src/main.ts#L39)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Is this supposed to say Wordlist instead of text collection?
</blockquote></details>

Whoops. You caught me CTRL+C CTRL+V-ing

**Review by rolfheij-sil — COMMENTED** [review]
Thanks! Note that I also moved the word count into the word column header in the word list table

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3#-:-Ni0Lv7jCP2SUvONzSt1:bmvzp2h)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

**Review by katherinejensen00 — APPROVED** [review]
This looks great. Thanks for all of your work on this!

**Review by katherinejensen00 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
