### PR TITLE
Generate word list from back-end, and some other small fixes

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4)* status: 0 of 6 files reviewed, 3 unresolved discussions

___
*[`src/main.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAgtFa9-_74xi5GspR:-NiAgtFa9-_74xi5GspS:bs5yxw5) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L26)):*
> ```XML
> 
> // MOVE TO TYPES FILE
> enum Scope {
> ```

Importing the Scope enum from the types file gave some issues that I don't know how to resolve. So I just copied it to every file that needed it as a temporary fix
___
*[`src/main.ts` line 255 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAhETRAzZdIlF6ed4L:-NiAhETRAzZdIlF6ed4M:b1gvn53) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L255)):*
> ```XML
>   );
> 
>   papi.webViews.getWebView(WORD_LIST_WEB_VIEW_TYPE, undefined, { existingId: '?' });
> ```

@lyonsil This resolves the issue of the Word List being open by default
___
*[`src/word-list.web-view.tsx` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAhRIa7oOwhicGXkeD:-NiAhRIa7oOwhicGXkeE:bgv8nx0) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/word-list.web-view.tsx#L41)):*
> ```XML
>   const wordListDataProvider = useDataProvider<WordListDataProvider>('wordList');
> 
>   const [wordList, , loadingWordList] = useData.WordList<WordListDataTypes, 'WordList'>(
> ```

@lyonsil This resolves the issue of the UI being frozen whenever the Word List updates

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome!! Thanks for the great work on this.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-:-NiAnhG25fszTTBYHMkA:b5lho5s)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`src/main.ts` line 255 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAhETRAzZdIlF6ed4L:-NiAmJhJ9VWutfDAAMuC:bmo1owx) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L255)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@lyonsil This resolves the issue of the Word List being open by default
</blockquote></details>

Actually I believe this line needs to be removed entirely to prevent the word list from being open by default. I believe this will open the word list in a new panel if it is not present already.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for all the help!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-:-NiApEMV3KLn2MiVEzTJ:bdda62x)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/main.ts` line 255 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAhETRAzZdIlF6ed4L:-NiApFuZB9tf29VOezoh:b-5h6jsj) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L255)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually I believe this line needs to be removed entirely to prevent the word list from being open by default. I believe this will open the word list in a new panel if it is not present already.
</blockquote></details>

Whoops, you're right. Fixed it

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/main.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAgtFa9-_74xi5GspR:-NiArpzM4PTU7mNvq4Ur:b-gtxlni) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Importing the Scope enum from the types file gave some issues that I don't know how to resolve. So I just copied it to every file that needed it as a temporary fix
</blockquote></details>

Please add a "TODO" to the front of this so that grepping will find this.  Alternatively, if there is an open ticket please put the ticket URL here.
___
*[`src/word-list.web-view.tsx` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAhRIa7oOwhicGXkeD:-NiArdwX-s5kMwKzvqdE:b4c9lyr) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/word-list.web-view.tsx#L41)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

@lyonsil This resolves the issue of the UI being frozen whenever the Word List updates
</blockquote></details>

:thumbsup: 
___
*[`src/word-list.web-view.tsx` line 104 at r3](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiArGw95Qp1rCKCV_BI:-NiArGw95Qp1rCKCV_BJ:b-5oj4em) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/002cc8e8e3f09a09df7b10d3885e8f0b817b229e/src/word-list.web-view.tsx#L104)):*
> ```XML
>         />
>       </div>
>       {loadingWordList ? (
> ```

I had to remove something very much like this from the resource viewer because we would periodically get stuck with the message about data being generated/loaded.  I'm hoping the slower nature of building the word list will help us avoid problems here, but it's possible we'll have to drop `loadingWordList`, too.

**Review by lyonsil — COMMENTED** [review]
Thanks for the work on this.  Just one small change requested.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-:-NiAsaDCDF5s2mjFJL2w:bbsmyj3)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/main.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiAgtFa9-_74xi5GspR:-NiAvnW-CJcZ3f66jXxI:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/8d4a9110604f9d8363d008fc6e762b3e593814a6/src/main.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Please add a "TODO" to the front of this so that grepping will find this.  Alternatively, if there is an open ticket please put the ticket URL here.
</blockquote></details>

Done.
___
*[`src/word-list.web-view.tsx` line 104 at r3](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-NiArGw95Qp1rCKCV_BI:-NiAvr0y3BHqSkT3lj9Y:b-gooich) ([raw file](https://github.com/paranext/paranext-extension-word-list/blob/002cc8e8e3f09a09df7b10d3885e8f0b817b229e/src/word-list.web-view.tsx#L104)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I had to remove something very much like this from the resource viewer because we would periodically get stuck with the message about data being generated/loaded.  I'm hoping the slower nature of building the word list will help us avoid problems here, but it's possible we'll have to drop `loadingWordList`, too.
</blockquote></details>

I didn't see any issues with it so far, but I'll keep an eye out for it

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-:-NiAwg_y9gC-JGjY-duj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-word-list/4#-:-NiAyGdaD_50eZozfGe3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
